### ISSUE TITLE
Activities not working?

### ISSUE THREAD

**Issue by mrjesseking** [reneboer/vera-Harmony-Hub#10]
Rene,

Thank you for all your work with the Harmony Hub plugin, I can see that you have been actively supporting this plugin for years. I recently got a harmony hub hoping to get some Lutron Serena shades working with Vera.  After setting up the hub I can see a set of activity mappings associated with the shades and those activities were assigned to buttons.  The associated actions show up as buttons within the "control" menu of the Harmony app.  However, when I click on the buttons they will not perform the associated harmony action.  I have also tried adding the activities to Vera scenes without success. 

I did have some success getting vera to send (delayed) IR signals to a TV using the devices menu so I know Vera can send commands to the harmony hub successfully.    However, there seems to be some issue getting Vera to execute activity commands through Harmony.  Do you have any suggestions?

Thanks,

Jesse

Hub configuration version: 105 
Hub software version: 4.15.250

**Comment by reneboer** [comment]
Hi Jesse,
Sorry, missed your question. I assume the Lutron shades communicate with the Hub via IP and not IR? IP devices work slightly different and I would need some debug information to find out if it can be made working. Can you get the config via an http request as described here : https://github.com/reneboer/vera-Harmony-Hub/wiki/HTTP-request-command-details for the Lutron devices and I can see what may be needed.

Cheers Rene

**Comment by reneboer** [comment]
Closing as no replies
